from django.urls import path
from interfaces.api import auth_views
from interfaces.api import housekeeping_views
from interfaces.api import service_order_views

urlpatterns = [
    path("me", auth_views.MeView.as_view(), name="auth-me"),
    path("auth/signup", auth_views.SignupView.as_view(), name="auth-signup"),
    path("auth/login", auth_views.LoginView.as_view(), name="auth-login"),
    path("auth/logout", auth_views.LogoutView.as_view(), name="auth-logout"),
    path("auth/refresh", auth_views.RefreshView.as_view(), name="auth-refresh"),
    path("auth/forgot-password", auth_views.ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password", auth_views.ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/activate", auth_views.ActivateInviteView.as_view(), name="auth-activate"),
    path("users", auth_views.UserListCreateView.as_view(), name="user-list-create"),
    path("roles", auth_views.RoleListView.as_view(), name="role-list"),
    path("roles/<int:role_id>", auth_views.RoleDetailView.as_view(), name="role-detail"),
    path("roles/<int:role_id>/permissions", auth_views.RolePermissionListCreateView.as_view(), name="role-permission-list-create"),
    path("roles/<int:role_id>/permissions/<int:permission_id>", auth_views.RolePermissionDetailView.as_view(), name="role-permission-detail"),
    path("permissions", auth_views.PermissionListCreateView.as_view(), name="permission-list-create"),
    path("permissions/<int:permission_id>", auth_views.PermissionDetailView.as_view(), name="permission-detail"),
    path("organizations", auth_views.OrganizationListCreateView.as_view(), name="org-list-create"),
    path("organizations/<int:org_id>", auth_views.OrganizationDetailView.as_view(), name="org-detail"),
    path("properties", auth_views.PropertyListCreateView.as_view(), name="property-list-create"),
    path("properties/<int:property_id>", auth_views.PropertyDetailView.as_view(), name="property-detail"),
    path("departments", auth_views.DepartmentListCreateView.as_view(), name="department-list-create"),
    path("departments/<int:department_id>", auth_views.DepartmentDetailView.as_view(), name="department-detail"),
    path("users/<int:user_id>", auth_views.UserDetailView.as_view(), name="user-detail"),
    path("users/<int:user_id>/roles", auth_views.UserRoleListCreateView.as_view(), name="user-role-list-create"),
    path("users/<int:user_id>/roles/<int:role_id>", auth_views.UserRoleDetailView.as_view(), name="user-role-detail"),
    path("users/<int:user_id>/properties", auth_views.UserPropertyListCreateView.as_view(), name="user-property-list-create"),
    path("users/<int:user_id>/properties/<int:property_id>", auth_views.UserPropertyDetailView.as_view(), name="user-property-detail"),
    path("users/<int:user_id>/departments", auth_views.UserDepartmentListCreateView.as_view(), name="user-department-list-create"),
    path("users/<int:user_id>/departments/<int:department_id>", auth_views.UserDepartmentDetailView.as_view(), name="user-department-detail"),
    path("users/<int:user_id>/invite", auth_views.UserInviteView.as_view(), name="user-invite"),
    path("users/<int:user_id>/suspend", auth_views.UserSuspendView.as_view(), name="user-suspend"),
    path("users/<int:user_id>/reactivate", auth_views.UserReactivateView.as_view(), name="user-reactivate"),
    path("audit-logs", auth_views.AuditLogListView.as_view(), name="audit-logs"),
    path("service-orders", service_order_views.ServiceOrderListCreateView.as_view(), name="service-order-list-create"),
    path("service-orders/<int:order_id>", service_order_views.ServiceOrderDetailView.as_view(), name="service-order-detail"),
    path("service-orders/<int:order_id>/assign", service_order_views.ServiceOrderAssignView.as_view(), name="service-order-assign"),
    path("service-orders/<int:order_id>/reassign", service_order_views.ServiceOrderAssignView.as_view(), name="service-order-reassign"),
    path("service-orders/<int:order_id>/start", service_order_views.ServiceOrderStartView.as_view(), name="service-order-start"),
    path("service-orders/<int:order_id>/hold", service_order_views.ServiceOrderHoldView.as_view(), name="service-order-hold"),
    path("service-orders/<int:order_id>/complete", service_order_views.ServiceOrderCompleteView.as_view(), name="service-order-complete"),
    path("service-orders/<int:order_id>/defer", service_order_views.ServiceOrderDeferView.as_view(), name="service-order-defer"),
    path("service-orders/<int:order_id>/void", service_order_views.ServiceOrderVoidView.as_view(), name="service-order-void"),
    path("service-orders/<int:order_id>/attachments", service_order_views.ServiceOrderAttachmentView.as_view(), name="service-order-attachments"),
    path("service-orders/<int:order_id>/remarks", service_order_views.ServiceOrderRemarkView.as_view(), name="service-order-remarks"),
    path("service-orders/<int:order_id>/costs", service_order_views.ServiceOrderCostUpdateView.as_view(), name="service-order-costs"),
    path("housekeeping/room-status", housekeeping_views.RoomStatusUpsertView.as_view(), name="housekeeping-room-status"),
    path("housekeeping/tasks", housekeeping_views.HousekeepingTaskListView.as_view(), name="housekeeping-task-list"),
    path("housekeeping/tasks/<int:task_id>", housekeeping_views.HousekeepingTaskDetailView.as_view(), name="housekeeping-task-detail"),
    path("housekeeping/tasks/<int:task_id>/start", housekeeping_views.HousekeepingTaskStartView.as_view(), name="housekeeping-task-start"),
    path("housekeeping/tasks/<int:task_id>/complete", housekeeping_views.HousekeepingTaskCompleteView.as_view(), name="housekeeping-task-complete"),
    path("housekeeping/tasks/<int:task_id>/verify", housekeeping_views.HousekeepingTaskVerifyView.as_view(), name="housekeeping-task-verify"),
    path("housekeeping/tasks/<int:task_id>/cancel", housekeeping_views.HousekeepingTaskCancelView.as_view(), name="housekeeping-task-cancel"),
    path("housekeeping/tasks/<int:task_id>/reopen", housekeeping_views.HousekeepingTaskReopenView.as_view(), name="housekeeping-task-reopen"),
    path("housekeeping/tasks/generate", housekeeping_views.HousekeepingTaskGenerateView.as_view(), name="housekeeping-task-generate"),
    path("housekeeping/tasks/assign", housekeeping_views.HousekeepingTaskAssignView.as_view(), name="housekeeping-task-assign"),
    path("housekeeping/tasks/reassign-overdue", housekeeping_views.HousekeepingTaskReassignOverdueView.as_view(), name="housekeeping-task-reassign-overdue"),
    path("housekeeping/kpi/summary", housekeeping_views.HousekeepingKPISummaryView.as_view(), name="housekeeping-kpi-summary"),
    path("housekeeping/kpi/staff-performance", housekeeping_views.HousekeepingKPIStaffPerformanceView.as_view(), name="housekeeping-kpi-staff-performance"),
    path("housekeeping/kpi/room-turnaround", housekeeping_views.HousekeepingKPIRoomTurnaroundView.as_view(), name="housekeeping-kpi-room-turnaround"),
    path("pms/room-status/sync", housekeeping_views.PMSRoomStatusSyncView.as_view(), name="pms-room-status-sync"),
    path("pms/room-status", housekeeping_views.PMSRoomStatusPullView.as_view(), name="pms-room-status-pull"),
    path("pms/housekeeping-tasks/sync", housekeeping_views.PMSTaskSyncView.as_view(), name="pms-housekeeping-task-sync"),
]
