import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useAuth } from '../../../features/auth/authContext'
import { useActivateReportSchedule, useCreateReportDefinition, useCreateReportSchedule, useDeactivateReportSchedule, useDepartmentPerformance, useDownloadReport, useExecutiveSummary, useReportDefinitionDetail, useReportDefinitions, useReportingAuditLogs, useReportingCompliance, useReportingCosts, useReportingEnergy, useReportingSla, useReportRunDetail, useReportRuns, useReportSchedules, useRunDueReportSchedules, useRunReport, useUpdateReportDefinition, useUpdateReportSchedule } from '../hooks/useReporting'
import type { Grouping, ReportType, ScheduleFrequency, ScheduleOutputFormat } from '../types/reporting.types'

const safe = (v: unknown) => { const n = Number(v); return Number.isFinite(n) ? n : 0 }
const fmt = (v: unknown, d = 2) => safe(v).toFixed(d)
const reportTypes: ReportType[] = ['OPERATIONAL_SUMMARY', 'DEPARTMENT_PERFORMANCE', 'SLA_REPORT', 'COST_REPORT', 'COMPLIANCE_REPORT', 'ENERGY_REPORT', 'CUSTOM']
const groupings: Grouping[] = ['day', 'week', 'month', 'quarter']
const departments = ['housekeeping', 'maintenance', 'guest_complaints', 'guest_requests', 'inspections', 'risk_compliance', 'food_beverage', 'energy', 'projects']
const frequencies: ScheduleFrequency[] = ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY']
const scheduleFormats: ScheduleOutputFormat[] = ['EXCEL', 'PDF']

function ReportingFilters({ params, setParams }: { params: URLSearchParams; setParams: (v: URLSearchParams) => void }) {
  const u = (k: string, v: string) => { const n = new URLSearchParams(params); if (v) n.set(k, v); else n.delete(k); setParams(n) }
  return <div className='grid-form three'><input aria-label='date_from' className='input' type='date' value={params.get('date_from') || ''} onChange={(e) => u('date_from', e.target.value)} /><input aria-label='date_to' className='input' type='date' value={params.get('date_to') || ''} onChange={(e) => u('date_to', e.target.value)} /><input aria-label='property_id' className='input' placeholder='property_id' value={params.get('property_id') || ''} onChange={(e) => u('property_id', e.target.value)} /><input aria-label='department_id' className='input' placeholder='department_id' value={params.get('department_id') || ''} onChange={(e) => u('department_id', e.target.value)} /><input aria-label='module' className='input' placeholder='module' value={params.get('module') || ''} onChange={(e) => u('module', e.target.value)} /><select aria-label='grouping' className='input' value={params.get('grouping') || 'day'} onChange={(e) => u('grouping', e.target.value)}>{groupings.map((g) => <option key={g} value={g}>{g}</option>)}</select></div>
}

function KpiCard({ label, value }: { label: string; value: unknown }) { return <article className='glass panel'><h3>{label}</h3><p>{fmt(value)}</p></article> }

export function ExecutiveDashboardPage() {
  const { auth } = useAuth(); const [params, setParams] = useSearchParams(); const q = useMemo(() => ({ org_id: auth?.user?.org_id || 0, date_from: params.get('date_from') || undefined, date_to: params.get('date_to') || undefined, property_id: params.get('property_id') || undefined, department_id: params.get('department_id') || undefined, module: params.get('module') || undefined, grouping: (params.get('grouping') as Grouping) || 'day' }), [auth?.user?.org_id, params])
  const exec = useExecutiveSummary(auth?.accessToken, q); const sla = useReportingSla(auth?.accessToken, q); const costs = useReportingCosts(auth?.accessToken, q); const comp = useReportingCompliance(auth?.accessToken, q); const energy = useReportingEnergy(auth?.accessToken, q)
  const loading = exec.loading || sla.loading || costs.loading || comp.loading || energy.loading
  const error = exec.error || sla.error || costs.error || comp.error || energy.error
  return <div className='page full'><div className='glass panel'><div className='section-head'><h2>Executive Dashboard</h2><button className='button secondary small' onClick={() => { void exec.reload(); void sla.reload(); void costs.reload(); void comp.reload(); void energy.reload() }}>Retry</button></div><ReportingFilters params={params} setParams={setParams} />{loading ? <p className='helper'>Loading dashboard...</p> : null}{error ? <p className='error-text'>{error}</p> : null}<div className='cards-grid'><KpiCard label='Average Resolution Hours' value={exec.data?.average_resolution_hours} /><KpiCard label='Total Operational Cost' value={costs.data?.total_operational_cost ?? exec.data?.total_operational_cost} /><KpiCard label='Compliance Rate %' value={comp.data?.compliance_rate ?? exec.data?.compliance_rate} /><KpiCard label='Guest Satisfaction' value={exec.data?.guest_satisfaction_score} /><KpiCard label='Energy Efficiency KPI' value={energy.data?.energy_efficiency_kpi ?? exec.data?.energy_efficiency_kpi} /><KpiCard label='SLA Compliance %' value={sla.data?.sla_compliance_percent} /></div><div className='table-wrap'><table className='data-table'><thead><tr><th>Module</th><th>Open</th><th>Completed</th><th>Overdue</th></tr></thead><tbody>{Object.keys(exec.data?.open_tasks_by_module || {}).map((m) => <tr key={m}><td>{m}</td><td>{safe(exec.data?.open_tasks_by_module[m])}</td><td>{safe(exec.data?.completed_tasks_by_module[m])}</td><td>{safe(exec.data?.overdue_items_by_module[m])}</td></tr>)}</tbody></table></div></div></div>
}

export function DepartmentDashboardsPage() {
  const { auth } = useAuth(); const nav = useNavigate(); const [params, setParams] = useSearchParams(); const q = useMemo(() => ({ org_id: auth?.user?.org_id || 0, date_from: params.get('date_from') || undefined, date_to: params.get('date_to') || undefined, property_id: params.get('property_id') || undefined, department_id: params.get('department_id') || undefined, module: params.get('module') || departments[0], grouping: (params.get('grouping') as Grouping) || 'day' }), [auth?.user?.org_id, params]); const perf = useDepartmentPerformance(auth?.accessToken, q)
  const u = (k: string, v: string) => { const n = new URLSearchParams(params); if (v) n.set(k, v); else n.delete(k); setParams(n) }
  const rows = Object.keys(perf.data?.open_tasks_by_module || {})
  return <div className='page full'><div className='glass panel'><h2>Department KPI Dashboards</h2><div className='grid-form three'><select aria-label='department selector' className='input' value={params.get('module') || departments[0]} onChange={(e) => u('module', e.target.value)}>{departments.map((d) => <option key={d} value={d}>{d}</option>)}</select><input className='input' placeholder='property_id' value={params.get('property_id') || ''} onChange={(e) => u('property_id', e.target.value)} /><input className='input' type='date' value={params.get('date_from') || ''} onChange={(e) => u('date_from', e.target.value)} /></div>{perf.loading ? <p>Loading department KPI...</p> : null}{perf.error ? <p className='error-text'>{perf.error}</p> : null}<div className='cards-grid'><KpiCard label='Open Items' value={rows.reduce((a, m) => a + safe(perf.data?.open_tasks_by_module[m]), 0)} /><KpiCard label='Completed Items' value={rows.reduce((a, m) => a + safe(perf.data?.completed_tasks_by_module[m]), 0)} /><KpiCard label='Overdue Items' value={rows.reduce((a, m) => a + safe(perf.data?.overdue_items_by_module[m]), 0)} /><KpiCard label='Compliance %' value={perf.data?.compliance_rate} /><KpiCard label='Avg Resolution Hrs' value={perf.data?.average_resolution_hours} /><KpiCard label='Operational Cost' value={perf.data?.total_operational_cost} /></div><div className='table-wrap'><table className='data-table'><thead><tr><th>Module</th><th>Open</th><th>Completed</th><th>Overdue</th><th>Drill-down</th></tr></thead><tbody>{rows.map((m) => <tr key={m}><td>{m}</td><td>{safe(perf.data?.open_tasks_by_module[m])}</td><td>{safe(perf.data?.completed_tasks_by_module[m])}</td><td>{safe(perf.data?.overdue_items_by_module[m])}</td><td><button className='button secondary small' onClick={() => nav(`/${m.replace('_', '-')}`)}>Open module</button></td></tr>)}</tbody></table></div></div></div>
}

export function ReportBuilderPage() {
  const { auth } = useAuth(); const create = useCreateReportDefinition(); const updateDef = useUpdateReportDefinition(); const defs = useReportDefinitions(auth?.accessToken); const [selectedId, setSelectedId] = useState<number | null>(null); const detail = useReportDefinitionDetail(auth?.accessToken, selectedId || undefined)
  const [form, setForm] = useState({ report_code: '', name: '', description: '', module_scope: 'service_orders', report_type: 'OPERATIONAL_SUMMARY' as ReportType, default_filters: '{}', columns_config: '[]', chart_config: '{}', is_active: true }); const [dirty, setDirty] = useState(false); const [error, setError] = useState(''); const [preview, setPreview] = useState('')
  useEffect(() => { const onBeforeUnload = (e: BeforeUnloadEvent) => { if (!dirty) return; e.preventDefault(); e.returnValue = '' }; window.addEventListener('beforeunload', onBeforeUnload); return () => window.removeEventListener('beforeunload', onBeforeUnload) }, [dirty])
  useEffect(() => { if (!detail.data) return; setForm({ report_code: detail.data.report_code, name: detail.data.name, description: detail.data.description || '', module_scope: (detail.data.module_scope || []).join(','), report_type: detail.data.report_type, default_filters: JSON.stringify(detail.data.default_filters || {}), columns_config: JSON.stringify(detail.data.columns_config || []), chart_config: JSON.stringify(detail.data.chart_config || {}), is_active: detail.data.is_active }); setDirty(false) }, [detail.data?.id])
  const save = async () => { if (!auth?.accessToken) return; setError(''); if (!form.report_code.trim() || !form.name.trim()) return setError('report_code and name are required.'); try { const payload = { report_code: form.report_code.trim().toUpperCase(), name: form.name.trim(), description: form.description, module_scope: form.module_scope.split(',').map((x) => x.trim()).filter(Boolean), report_type: form.report_type, default_filters: JSON.parse(form.default_filters || '{}'), columns_config: JSON.parse(form.columns_config || '[]'), chart_config: JSON.parse(form.chart_config || '{}'), is_active: form.is_active }; if (selectedId) await updateDef(auth.accessToken, selectedId, payload); else await create(auth.accessToken, payload); setDirty(false); await defs.reload() } catch (e: any) { setError(e?.message || 'Failed to save definition') } }
  const runPreview = () => { try { const parsed = JSON.parse(form.default_filters || '{}'); setPreview(JSON.stringify({ report_type: form.report_type, filters: parsed, columns: JSON.parse(form.columns_config || '[]') }, null, 2)) } catch { setPreview('Invalid JSON in filters/columns/chart config') } }
  return <div className='page full'><div className='glass panel'><h2>Custom Report Builder</h2><div className='grid-form two'><label className='field'>Existing Definitions<select className='input' value={selectedId || ''} onChange={(e) => setSelectedId(e.target.value ? Number(e.target.value) : null)}><option value=''>New Definition</option>{(defs.data?.results || []).map((d) => <option key={d.id} value={d.id}>{d.report_code} - {d.name}</option>)}</select></label><label className='field'>report_code<input aria-label='report_code' className='input' value={form.report_code} onChange={(e) => { setForm((p) => ({ ...p, report_code: e.target.value })); setDirty(true) }} /></label><label className='field'>name<input aria-label='name' className='input' value={form.name} onChange={(e) => { setForm((p) => ({ ...p, name: e.target.value })); setDirty(true) }} /></label><label className='field'>module_scope<input aria-label='module_scope' className='input' value={form.module_scope} onChange={(e) => { setForm((p) => ({ ...p, module_scope: e.target.value })); setDirty(true) }} /></label><label className='field'>report_type<select aria-label='report_type' className='input' value={form.report_type} onChange={(e) => { setForm((p) => ({ ...p, report_type: e.target.value as ReportType })); setDirty(true) }}>{reportTypes.map((t) => <option key={t} value={t}>{t}</option>)}</select></label><label className='field'>is_active<input aria-label='is_active' type='checkbox' checked={form.is_active} onChange={(e) => { setForm((p) => ({ ...p, is_active: e.target.checked })); setDirty(true) }} /></label></div><label className='field'>description<textarea className='input' rows={2} value={form.description} onChange={(e) => { setForm((p) => ({ ...p, description: e.target.value })); setDirty(true) }} /></label><div className='grid-form three'><label className='field'>default_filters<textarea aria-label='default_filters' className='input' rows={4} value={form.default_filters} onChange={(e) => { setForm((p) => ({ ...p, default_filters: e.target.value })); setDirty(true) }} /></label><label className='field'>columns_config<textarea aria-label='columns_config' className='input' rows={4} value={form.columns_config} onChange={(e) => { setForm((p) => ({ ...p, columns_config: e.target.value })); setDirty(true) }} /></label><label className='field'>chart_config<textarea aria-label='chart_config' className='input' rows={4} value={form.chart_config} onChange={(e) => { setForm((p) => ({ ...p, chart_config: e.target.value })); setDirty(true) }} /></label></div>{dirty ? <p className='hint'>You have unsaved changes.</p> : null}{error ? <p className='error-text'>{error}</p> : null}<div className='actions-row'><button className='button' onClick={() => void save()}>Save</button><button className='button secondary small' onClick={runPreview}>Preview</button></div>{preview ? <pre>{preview}</pre> : null}</div></div>
}

export function ReportDefinitionsPage() { const { auth } = useAuth(); const defs = useReportDefinitions(auth?.accessToken); const nav = useNavigate(); return <div className='page full'><div className='glass panel'><div className='section-head'><h2>Report Definitions</h2><button className='button' onClick={() => nav('/reporting/report-builder')}>New</button></div>{defs.loading ? <p>Loading...</p> : null}{defs.error ? <p className='error-text'>{defs.error}</p> : null}<div className='table-wrap'><table className='data-table'><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Active</th><th>Action</th></tr></thead><tbody>{(defs.data?.results || []).map((d) => <tr key={d.id}><td>{d.report_code}</td><td>{d.name}</td><td>{d.report_type}</td><td>{d.is_active ? 'Yes' : 'No'}</td><td><button className='button secondary small' onClick={() => nav(`/reporting/report-builder?definitionId=${d.id}`)}>Edit</button></td></tr>)}</tbody></table></div></div></div> }

export function ReportRunsPage() {
  const { auth } = useAuth(); const defs = useReportDefinitions(auth?.accessToken); const runs = useReportRuns(auth?.accessToken); const runReport = useRunReport(); const downloadReport = useDownloadReport(); const [form, setForm] = useState({ report_definition_id: '', output_format: 'JSON', filters: '{}' }); const [msg, setMsg] = useState('')
  const start = async () => { if (!auth?.accessToken || !form.report_definition_id) return; setMsg(''); try { await runReport(auth.accessToken, { report_definition_id: Number(form.report_definition_id), output_format: form.output_format as any, filters: JSON.parse(form.filters || '{}') }); setMsg('Report run requested'); await runs.reload() } catch (e: any) { setMsg(e?.message || 'Run failed') } }
  const download = async (id: number) => { if (!auth?.accessToken) return; try { const res = await downloadReport(auth.accessToken, id); setMsg(`Generated: ${res.file_path} (${res.size} bytes)`) } catch (e: any) { setMsg(e?.message || 'Download failed') } }
  return <div className='page full'><div className='glass panel'><h2>Report Runs</h2><div className='grid-form three'><select aria-label='report_definition_id' className='input' value={form.report_definition_id} onChange={(e) => setForm((p) => ({ ...p, report_definition_id: e.target.value }))}><option value=''>Select definition</option>{(defs.data?.results || []).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><select aria-label='output_format' className='input' value={form.output_format} onChange={(e) => setForm((p) => ({ ...p, output_format: e.target.value }))}><option>JSON</option><option>EXCEL</option><option>PDF</option></select><textarea aria-label='filters' className='input' value={form.filters} onChange={(e) => setForm((p) => ({ ...p, filters: e.target.value }))} /></div><button className='button' onClick={() => void start()}>Run Report</button>{msg ? <p className={msg.includes('failed') ? 'error-text' : 'hint'}>{msg}</p> : null}<div className='table-wrap'><table className='data-table'><thead><tr><th>ID</th><th>Status</th><th>Format</th><th>Created</th><th>Completed</th><th>Error</th><th>Download</th></tr></thead><tbody>{(runs.data?.results || []).map((r) => <tr key={r.id}><td>{r.id}</td><td><span className='badge neutral'>{r.status}</span></td><td>{r.output_format}</td><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.completed_at ? new Date(r.completed_at).toLocaleString() : '-'}</td><td>{r.error_message || '-'}</td><td><button className='button secondary small' disabled={r.status !== 'COMPLETED'} onClick={() => void download(r.id)}>Download</button></td></tr>)}</tbody></table></div></div></div>
}

export function ReportRunDetailPage() { const { auth } = useAuth(); const { id } = useParams(); const run = useReportRunDetail(auth?.accessToken, id ? Number(id) : undefined); return <div className='page full'><div className='glass panel'><h2>Report Run Detail</h2>{run.loading ? <p>Loading...</p> : null}{run.error ? <p className='error-text'>{run.error}</p> : null}{run.data ? <pre>{JSON.stringify(run.data, null, 2)}</pre> : null}</div></div> }

export function ReportSchedulesPage() {
  const { auth } = useAuth(); const defs = useReportDefinitions(auth?.accessToken); const list = useReportSchedules(auth?.accessToken); const create = useCreateReportSchedule(); const update = useUpdateReportSchedule(); const activate = useActivateReportSchedule(); const deactivate = useDeactivateReportSchedule(); const runDue = useRunDueReportSchedules(); const [editing, setEditing] = useState<number | null>(null); const [f, setF] = useState({ report_definition_id: '', name: '', frequency_type: 'DAILY' as ScheduleFrequency, frequency_config: '{}', recipients: '', output_format: 'PDF' as ScheduleOutputFormat, filters: '{}', is_active: true }); const [msg, setMsg] = useState('')
  const submit = async () => { if (!auth?.accessToken) return; setMsg(''); if (!f.report_definition_id || !f.name.trim()) return setMsg('Definition and name are required.'); const recipients = f.recipients.split(',').map((x) => x.trim()).filter(Boolean); if (recipients.some((r) => !/^\S+@\S+\.\S+$/.test(r))) return setMsg('Invalid recipient email.'); try { const payload = { report_definition_id: Number(f.report_definition_id), name: f.name, frequency_type: f.frequency_type, frequency_config: JSON.parse(f.frequency_config || '{}'), recipients, output_format: f.output_format, filters: JSON.parse(f.filters || '{}'), is_active: f.is_active }; if (editing) await update(auth.accessToken, editing, payload); else await create(auth.accessToken, payload); setEditing(null); await list.reload() } catch (e: any) { setMsg(e?.message || 'Save failed') } }
  const toggle = async (id: number, on: boolean) => { if (!auth?.accessToken) return; if (on) await deactivate(auth.accessToken, id); else await activate(auth.accessToken, id); await list.reload() }
  const runDueNow = async () => { if (!auth?.accessToken) return; const out = await runDue(auth.accessToken); setMsg(`Checked ${out.schedules_checked}, generated ${out.reports_generated}, emailed ${out.emails_sent}`) }
  return <div className='page full'><div className='glass panel'><div className='section-head'><h2>Report Schedules</h2><button className='button secondary small' onClick={() => void runDueNow()}>Run Due Schedules</button></div><div className='grid-form three'><select aria-label='schedule_report_definition_id' className='input' value={f.report_definition_id} onChange={(e) => setF((p) => ({ ...p, report_definition_id: e.target.value }))}><option value=''>Definition</option>{(defs.data?.results || []).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><input aria-label='schedule_name' className='input' placeholder='name' value={f.name} onChange={(e) => setF((p) => ({ ...p, name: e.target.value }))} /><select aria-label='schedule_frequency_type' className='input' value={f.frequency_type} onChange={(e) => setF((p) => ({ ...p, frequency_type: e.target.value as ScheduleFrequency }))}>{frequencies.map((x) => <option key={x}>{x}</option>)}</select><select aria-label='schedule_output_format' className='input' value={f.output_format} onChange={(e) => setF((p) => ({ ...p, output_format: e.target.value as ScheduleOutputFormat }))}>{scheduleFormats.map((x) => <option key={x}>{x}</option>)}</select><input aria-label='schedule_recipients' className='input' placeholder='emails comma-separated' value={f.recipients} onChange={(e) => setF((p) => ({ ...p, recipients: e.target.value }))} /><label className='field'>Active<input aria-label='schedule_is_active' type='checkbox' checked={f.is_active} onChange={(e) => setF((p) => ({ ...p, is_active: e.target.checked }))} /></label><textarea aria-label='schedule_frequency_config' className='input' placeholder='frequency_config json' value={f.frequency_config} onChange={(e) => setF((p) => ({ ...p, frequency_config: e.target.value }))} /><textarea aria-label='schedule_filters' className='input' placeholder='filters json' value={f.filters} onChange={(e) => setF((p) => ({ ...p, filters: e.target.value }))} /></div><button className='button' onClick={() => void submit()}>{editing ? 'Update' : 'Create'} Schedule</button>{msg ? <p className={msg.toLowerCase().includes('failed') || msg.toLowerCase().includes('invalid') ? 'error-text' : 'hint'}>{msg}</p> : null}<div className='table-wrap'><table className='data-table'><thead><tr><th>Name</th><th>Frequency</th><th>Active</th><th>Next Run</th><th>Last Run</th><th>Actions</th></tr></thead><tbody>{(list.data?.results || []).map((s) => <tr key={s.id}><td>{s.name}</td><td>{s.frequency_type}</td><td>{s.is_active ? 'Yes' : 'No'}</td><td>{s.next_run_at ? new Date(s.next_run_at).toLocaleString() : '-'}</td><td>{s.last_run_at ? new Date(s.last_run_at).toLocaleString() : '-'}</td><td><button className='button secondary small' onClick={() => void toggle(s.id, s.is_active)}>{s.is_active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div></div></div>
}

export function ReportingAuditLogsPage() {
  const { auth } = useAuth(); const [params, setParams] = useSearchParams(); const [meta, setMeta] = useState<Record<string, unknown> | null>(null)
  const q = useMemo(() => ({ org_id: auth?.user?.org_id || 0, page: Number(params.get('page') || 1), page_size: 20, sort_by: params.get('sort_by') || 'created_at', sort_dir: params.get('sort_dir') || 'desc', action: params.get('action') || undefined, target_type: params.get('target_type') || undefined, target_id: params.get('target_id') || undefined, date_from: params.get('date_from') || undefined, date_to: params.get('date_to') || undefined }), [auth?.user?.org_id, params])
  const logs = useReportingAuditLogs(auth?.accessToken, q)
  const pages = Math.max(1, Math.ceil((logs.data?.count || 0) / 20))
  const u = (k: string, v: string) => { const n = new URLSearchParams(params); if (v) n.set(k, v); else n.delete(k); if (k !== 'page') n.set('page', '1'); setParams(n) }
  return <div className='page full'><div className='glass panel'><h2>Reporting Audit Logs</h2><div className='grid-form three'><input aria-label='audit_action' className='input' placeholder='action' value={params.get('action') || ''} onChange={(e) => u('action', e.target.value)} /><input aria-label='audit_target_type' className='input' placeholder='target_type' value={params.get('target_type') || ''} onChange={(e) => u('target_type', e.target.value)} /><input aria-label='audit_date_from' className='input' type='date' value={params.get('date_from') || ''} onChange={(e) => u('date_from', e.target.value)} /></div>{logs.loading ? <p>Loading audit logs...</p> : null}{logs.error ? <p className='error-text'>{logs.error}</p> : null}<div className='table-wrap'><table className='data-table'><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>ID</th><th>Metadata</th></tr></thead><tbody>{(logs.data?.results || []).map((r) => <tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.actor_user_id || '-'}</td><td>{r.action}</td><td>{r.target_type}</td><td>{r.target_id}</td><td><button className='button secondary small' onClick={() => setMeta(r.metadata || {})}>Open</button></td></tr>)}</tbody></table></div><div className='pagination-row'><button className='button secondary small' disabled={(q.page as number) <= 1} onClick={() => u('page', String((q.page as number) - 1))}>Prev</button><span>Page {q.page as number} of {pages}</span><button className='button secondary small' disabled={(q.page as number) >= pages} onClick={() => u('page', String((q.page as number) + 1))}>Next</button></div>{meta ? <div className='card-section'><h3>Metadata</h3><pre>{JSON.stringify(meta, null, 2)}</pre><button className='button secondary small' onClick={() => setMeta(null)}>Close</button></div> : null}</div></div>
}
