# Generated by Django 5.0.6 on 2026-05-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_housekeeping_phase3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_code", models.CharField(max_length=64, unique=True)),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assets",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.department",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.room",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_assets",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetLifecycleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out Of Service"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=32,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_history",
                        to="core.asset",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_status_changes",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceLogbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("DIAGNOSIS", "Diagnosis"),
                            ("WORK_PERFORMED", "Work Performed"),
                            ("PART_USED", "Part Used"),
                            ("LABOR", "Labor"),
                            ("NOTE", "Note"),
                            ("COMPLETION_SUMMARY", "Completion Summary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logbook_entries",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_logbook_entries",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceLaborEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technician_id", models.BigIntegerField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=12)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_labor_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "logbook_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_entries",
                        to="core.maintenancelogbookentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenancePartEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255)),
                ("part_number", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "logbook_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_entries",
                        to="core.maintenancelogbookentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_number", models.CharField(max_length=64, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "Corrective"),
                            ("PREVENTIVE", "Preventive"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parts_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "labor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="core.asset",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_maintenance_tasks",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="core.department",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="core.property",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_maintenance_tasks",
                        to="core.user",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="core.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintenancelogbookentry",
            name="maintenance_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logbook_entries",
                to="core.maintenancetask",
            ),
        ),
        migrations.CreateModel(
            name="PMSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=16,
                    ),
                ),
                ("frequency_interval", models.PositiveIntegerField(default=1)),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pm_schedules",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pm_schedules",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="pm_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_tasks",
                to="core.pmschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["org", "status"], name="asset_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["org", "category"], name="asset_org_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["org", "property"], name="asset_org_property_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["org", "room"], name="asset_org_room_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["org", "department"], name="asset_org_dept_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["org", "criticality"], name="asset_org_criticality_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetlifecyclehistory",
            index=models.Index(
                fields=["asset", "changed_at"], name="asset_lifecycle_hist_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancelogbookentry",
            index=models.Index(
                fields=["maintenance_task", "created_at"],
                name="maint_logbook_task_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pmschedule",
            index=models.Index(
                fields=["is_active", "next_run_at"], name="pm_sched_active_next_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pmschedule",
            index=models.Index(
                fields=["asset", "is_active"], name="pm_sched_asset_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["org", "task_type"], name="maint_task_org_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["org", "status"], name="maint_task_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["org", "priority"], name="maint_task_org_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["org", "assigned_to"], name="maint_task_org_assignee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["asset", "status"], name="maint_task_asset_status_idx"
            ),
        ),
    ]
