# Generated by Django 5.0.6 on 2026-05-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_maint_task_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("complaint_number", models.CharField(max_length=64, unique=True)),
                ("guest_id", models.BigIntegerField(blank=True, null=True)),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_contact", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROOM_CLEANLINESS", "Room Cleanliness"),
                            ("MAINTENANCE", "Maintenance"),
                            ("NOISE", "Noise"),
                            ("STAFF_BEHAVIOR", "Staff Behavior"),
                            ("BILLING", "Billing"),
                            ("FOOD_BEVERAGE", "Food & Beverage"),
                            ("CHECK_IN_CHECK_OUT", "Check-In / Check-Out"),
                            ("SAFETY_SECURITY", "Safety & Security"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("TRIAGED", "Triaged"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("CONFIRMED", "Confirmed"),
                            ("REOPENED", "Reopened"),
                            ("CLOSED", "Closed"),
                            ("VOID", "Void"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("FRONT_DESK", "Front Desk"),
                            ("GUEST_PORTAL", "Guest Portal"),
                            ("PHONE", "Phone"),
                            ("EMAIL", "Email"),
                            ("STAFF", "Staff"),
                            ("PMS", "PMS"),
                            ("OTHER", "Other"),
                        ],
                        default="FRONT_DESK",
                        max_length=32,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("satisfaction_comment", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_guest_complaints",
                        to="core.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_guest_complaints",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaints",
                        to="core.department",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalated_guest_complaints",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaints",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaints",
                        to="core.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaints",
                        to="core.room",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_guest_complaints",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestComplaintEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escalation_level", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="core.guestcomplaint",
                    ),
                ),
                (
                    "escalated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_escalated_from",
                        to="core.user",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_escalated_to",
                        to="core.user",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_escalation_triggers",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestComplaintFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("follow_up_type", models.CharField(max_length=64)),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("MISSED", "Missed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_followups",
                        to="core.user",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="core.guestcomplaint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_guest_complaint_followups",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestComplaintStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("TRIAGED", "Triaged"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("CONFIRMED", "Confirmed"),
                            ("REOPENED", "Reopened"),
                            ("CLOSED", "Closed"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("TRIAGED", "Triaged"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("CONFIRMED", "Confirmed"),
                            ("REOPENED", "Reopened"),
                            ("CLOSED", "Closed"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_status_changes",
                        to="core.user",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.guestcomplaint",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="guestcomplaint",
            index=models.Index(
                fields=["property", "status"], name="guest_cmp_prop_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaint",
            index=models.Index(
                fields=["property", "severity"], name="guest_cmp_prop_severity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaint",
            index=models.Index(
                fields=["property", "category"], name="guest_cmp_prop_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaint",
            index=models.Index(fields=["assigned_to"], name="guest_cmp_assignee_idx"),
        ),
        migrations.AddIndex(
            model_name="guestcomplaint",
            index=models.Index(fields=["created_at"], name="guest_cmp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="guestcomplaintescalation",
            index=models.Index(
                fields=["complaint", "is_active"], name="guest_cmp_esc_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guestcomplaintescalation",
            constraint=models.UniqueConstraint(
                fields=("complaint", "escalation_level", "is_active"),
                name="uniq_guest_cmp_active_escalation_level",
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaintfollowup",
            index=models.Index(
                fields=["complaint", "status"], name="guest_cmp_followup_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaintfollowup",
            index=models.Index(
                fields=["assigned_to", "status"], name="gc_fu_assignee_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaintfollowup",
            index=models.Index(
                fields=["scheduled_at"], name="guest_cmp_followup_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestcomplaintstatushistory",
            index=models.Index(
                fields=["complaint", "changed_at"], name="guest_cmp_hist_changed_idx"
            ),
        ),
    ]
