# Generated by Django 5.0.6 on 2026-05-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_guestcomplaint_guestcomplaintescalation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestcomplaint",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestcomplaint",
            name="shift",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MORNING", "Morning"),
                    ("AFTERNOON", "Afternoon"),
                    ("NIGHT", "Night"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="guestcomplaint",
            name="vip_guest",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="GuestComplaintRoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROOM_CLEANLINESS", "Room Cleanliness"),
                            ("MAINTENANCE", "Maintenance"),
                            ("NOISE", "Noise"),
                            ("STAFF_BEHAVIOR", "Staff Behavior"),
                            ("BILLING", "Billing"),
                            ("FOOD_BEVERAGE", "Food & Beverage"),
                            ("CHECK_IN_CHECK_OUT", "Check-In / Check-Out"),
                            ("SAFETY_SECURITY", "Safety & Security"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("NIGHT", "Night"),
                        ],
                        max_length=16,
                    ),
                ),
                ("vip_only", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_routing_rules",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_routing_rules",
                        to="core.department",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_complaint_routing_rules",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"], name="gc_rule_active_prio_idx"
                    ),
                    models.Index(
                        fields=["category", "severity"], name="gc_rule_cat_sev_idx"
                    ),
                    models.Index(
                        fields=["property", "shift"], name="gc_rule_prop_shift_idx"
                    ),
                ],
            },
        ),
    ]
