# Generated by Django 5.0.6 on 2026-05-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_guestcomplaint_reported_at_guestcomplaint_shift_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionChecklistSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "response_type",
                    models.CharField(
                        choices=[("PASS_FAIL_NA", "Pass/Fail/NA")],
                        default="PASS_FAIL_NA",
                        max_length=32,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("non_compliance_trigger", models.BooleanField(default=False)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.inspectionchecklistsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspection_number", models.CharField(max_length=64, unique=True)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("PARTIAL", "Partial"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                        ],
                        default="PARTIAL",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_runs",
                        to="core.asset",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_inspection_runs",
                        to="core.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inspection_runs",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_runs",
                        to="core.department",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspected_runs",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_runs",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_runs",
                        to="core.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_runs",
                        to="core.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionRunHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_run_history",
                        to="core.user",
                    ),
                ),
                (
                    "inspection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.inspectionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionStepResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "evidence_attachment_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="core.inspectionchecklistitem",
                    ),
                ),
                (
                    "inspection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.inspectionrun",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_responses",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inspection_templates",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_templates",
                        to="core.department",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_templates",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_templates",
                        to="core.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_inspection_templates",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspectionrun",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="core.inspectiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="inspectionchecklistsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.inspectiontemplate",
            ),
        ),
        migrations.CreateModel(
            name="NonComplianceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("ITEM_FAIL", "Item Fail"),
                            ("FINAL_FAIL", "Final Fail"),
                            ("SCORE_BELOW_THRESHOLD", "Score Below Threshold"),
                            ("REPEAT_FAILURE", "Repeat Failure"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_compliance_alerts",
                        to="core.user",
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_compliance_alerts",
                        to="core.inspectionchecklistitem",
                    ),
                ),
                (
                    "inspection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_compliance_alerts",
                        to="core.inspectionrun",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_compliance_alerts",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inspectionchecklistitem",
            index=models.Index(
                fields=["section", "sort_order"], name="insp_item_sort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionchecklistitem",
            constraint=models.CheckConstraint(
                check=models.Q(("weight__gte", 0)), name="insp_item_weight_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrunhistory",
            index=models.Index(
                fields=["inspection_run", "created_at"],
                name="insp_history_run_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionstepresponse",
            index=models.Index(
                fields=["inspection_run", "responded_at"], name="insp_resp_run_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionstepresponse",
            constraint=models.UniqueConstraint(
                fields=("inspection_run", "checklist_item"),
                name="uniq_run_item_response",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectiontemplate",
            index=models.Index(
                fields=["org", "is_active"], name="insp_tpl_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectiontemplate",
            index=models.Index(
                fields=["org", "category"], name="insp_tpl_org_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["org", "status"], name="insp_run_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["org", "result"], name="insp_run_org_result_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["template", "created_at"], name="insp_run_template_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["property", "created_at"], name="insp_run_property_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["room", "created_at"], name="insp_run_room_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["asset", "created_at"], name="insp_run_asset_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionchecklistsection",
            index=models.Index(
                fields=["template", "sort_order"], name="insp_section_sort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionchecklistsection",
            constraint=models.CheckConstraint(
                check=models.Q(("weight__gte", 0)), name="insp_sec_weight_nonneg"
            ),
        ),
        migrations.AddIndex(
            model_name="noncompliancealert",
            index=models.Index(fields=["org", "status"], name="nca_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="noncompliancealert",
            index=models.Index(
                fields=["inspection_run", "status"], name="nca_run_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noncompliancealert",
            index=models.Index(
                fields=["alert_type", "status"], name="nca_type_status_idx"
            ),
        ),
    ]
