# Generated by Django 5.0.6 on 2026-05-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_compliancerequirement_compliancechecklistitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("RENOVATION", "Renovation"),
                            ("CONSTRUCTION", "Construction"),
                            ("MAINTENANCE_UPGRADE", "Maintenance Upgrade"),
                            ("COMPLIANCE_REMEDIATION", "Compliance Remediation"),
                            ("TECHNOLOGY", "Technology"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to="core.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_projects",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("project_status_changed", "Project Status Changed"),
                            ("project_progress_updated", "Project Progress Updated"),
                            ("snagging_item_created", "Snagging Item Created"),
                            ("snagging_item_resolved", "Snagging Item Resolved"),
                            ("technical_audit_created", "Technical Audit Created"),
                            ("technical_audit_completed", "Technical Audit Completed"),
                            ("attachment_added", "Attachment Added"),
                            ("comment_added", "Comment Added"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("message", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_timeline_entries",
                        to="core.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnaggingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snag_number", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FINISHING", "Finishing"),
                            ("ELECTRICAL", "Electrical"),
                            ("PLUMBING", "Plumbing"),
                            ("HVAC", "HVAC"),
                            ("CIVIL", "Civil"),
                            ("SAFETY", "Safety"),
                            ("QUALITY", "Quality"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("VERIFIED", "Verified"),
                            ("REOPENED", "Reopened"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("room_id", models.BigIntegerField(blank=True, null=True)),
                ("asset_id", models.BigIntegerField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_snagging_items",
                        to="core.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snagging_items",
                        to="core.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_snagging_items",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnaggingItemAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snagging_assignment_changes",
                        to="core.user",
                    ),
                ),
                (
                    "new_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snagging_new_assignments",
                        to="core.user",
                    ),
                ),
                (
                    "previous_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snagging_prev_assignments",
                        to="core.user",
                    ),
                ),
                (
                    "snagging_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_history",
                        to="core.snaggingitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnaggingItemStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("VERIFIED", "Verified"),
                            ("REOPENED", "Reopened"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("VERIFIED", "Verified"),
                            ("REOPENED", "Reopened"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snagging_status_changes",
                        to="core.user",
                    ),
                ),
                (
                    "snagging_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.snaggingitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_number", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("scope", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("PARTIAL", "Partial"),
                            ("OBSERVATION", "Observation"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("findings_summary", models.TextField(blank=True)),
                ("corrective_actions_required", models.BooleanField(default=False)),
                ("conducted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_technical_audits",
                        to="core.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_technical_audits",
                        to="core.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_audits",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["property"], name="project_property_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["department"], name="project_department_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["priority"], name="project_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="project_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["manager"], name="project_manager_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_at"], name="project_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projecttimeline",
            index=models.Index(
                fields=["project", "created_at"], name="project_timeline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snaggingitemassignmenthistory",
            index=models.Index(
                fields=["snagging_item", "changed_at"], name="snag_assign_hist_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snaggingitemstatushistory",
            index=models.Index(
                fields=["snagging_item", "changed_at"], name="snag_status_hist_idx"
            ),
        ),
    ]
