# Generated by Django 5.0.6 on 2026-05-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_project_projecttimeline_snaggingitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodBeverageBreakfastCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outlet_id", models.BigIntegerField()),
                ("service_date", models.DateField()),
                ("expected_guest_count", models.IntegerField(default=0)),
                ("actual_guest_count", models.IntegerField(default=0)),
                ("in_house_guest_count", models.IntegerField(default=0)),
                ("complimentary_count", models.IntegerField(default=0)),
                ("paid_count", models.IntegerField(default=0)),
                ("no_show_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_breakfast_counts",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_breakfast_counts",
                        to="core.property",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_recorded_breakfast_counts",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodBeverageOutletReadiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outlet_id", models.BigIntegerField()),
                ("readiness_date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                            ("ALL_DAY", "All Day"),
                            ("OTHER", "Other"),
                        ],
                        default="BREAKFAST",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY", "Ready"),
                            ("NOT_READY", "Not Ready"),
                            ("VERIFIED", "Verified"),
                            ("VOID", "Void"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "checklist_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("checklist_items", models.JSONField(blank=True, default=list)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_outlet_readiness",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_outlet_readiness",
                        to="core.property",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_verified_readiness",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodBeverageTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outlet_id", models.BigIntegerField()),
                ("task_number", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST_PREP", "Breakfast Prep"),
                            ("OUTLET_SETUP", "Outlet Setup"),
                            ("INVENTORY_CHECK", "Inventory Check"),
                            ("CLEANING", "Cleaning"),
                            ("SERVICE_SUPPORT", "Service Support"),
                            ("ISSUE_RESOLUTION", "Issue Resolution"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.TextField(blank=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_assigned_tasks",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_tasks",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fb_tasks",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
