# Generated by Django 5.0.6 on 2026-05-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_foodbeveragebreakfastcount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAPEXRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capex_number", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("BUDGET_RELEASED", "Budget Released"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("justification", models.TextField(blank=True)),
                ("business_impact", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_capex",
                        to="core.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_capex",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_requests",
                        to="core.department",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_requests",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_requests",
                        to="core.property",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_capex",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_capex",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("contract_type", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("RENEWAL_DUE", "Renewal Due"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("renewal_due_at", models.DateField(blank=True, null=True)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("attachment_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_contracts",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corporate_contracts",
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_contracts",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_contracts",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("po_number", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ORDERED", "Ordered"),
                            ("PARTIALLY_RECEIVED", "Partially Received"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("required_by", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("notes", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_purchase_orders",
                        to="core.user",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="core.corporatecontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_purchase_orders",
                        to="core.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="core.department",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="core.property",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_purchase_orders",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_purchase_orders",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("BLACKLISTED", "Blacklisted"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_suppliers",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_suppliers",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="core.supplier",
            ),
        ),
        migrations.AddField(
            model_name="corporatecontract",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="core.supplier",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("CAPEX_REQUEST", "CAPEX Request"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("approval_level", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("decision_comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["org", "entity_type", "entity_id"],
                        name="approval_org_entity_idx",
                    ),
                    models.Index(
                        fields=["approver", "status"],
                        name="approval_approver_status_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("org", "entity_type", "entity_id", "approval_level", "status"),
                name="uniq_pending_approval_per_level",
            ),
        ),
        migrations.AddIndex(
            model_name="capexrequest",
            index=models.Index(fields=["org", "status"], name="capex_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="capexrequest",
            index=models.Index(
                fields=["org", "requester"], name="capex_org_requester_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderlineitem",
            index=models.Index(
                fields=["purchase_order", "created_at"],
                name="po_line_item_po_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["org", "status"], name="supplier_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["org", "category"], name="supplier_org_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["org", "name"], name="supplier_org_name_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["org", "status"], name="po_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["org", "supplier"], name="po_org_supplier_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["org", "requester"], name="po_org_requester_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporatecontract",
            index=models.Index(
                fields=["org", "status"], name="contract_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporatecontract",
            index=models.Index(
                fields=["org", "supplier"], name="contract_org_supplier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporatecontract",
            index=models.Index(fields=["org", "owner"], name="contract_org_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="corporatecontract",
            index=models.Index(
                fields=["org", "expiry_date"], name="contract_org_expiry_idx"
            ),
        ),
    ]
