# Generated by Django 5.0.6 on 2026-05-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_capexrequest_corporatecontract_purchaseorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capexrequest",
            name="secondary_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_approved_capex",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="secondary_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_approved_purchase_orders",
                to="core.user",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("CAPEX_REQUEST", "CAPEX Request"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("approval_level", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("decision_comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_history",
                        to="core.user",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_history",
                        to="core.organization",
                    ),
                ),
                (
                    "request_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history_entries",
                        to="core.approvalrequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["org", "entity_type", "entity_id"],
                        name="approval_hist_org_entity_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "approval_level"],
                        name="approval_hist_entity_level_idx",
                    ),
                ],
            },
        ),
    ]
