# Generated by Django 5.0.6 on 2026-05-06 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_sustainabilitytarget_utilitycostrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDataMartRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("SCHEDULED", "Scheduled")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("modules_processed", models.JSONField(blank=True, default=list)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_data_mart_runs",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_code", models.CharField(max_length=96, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("module_scope", models.JSONField(blank=True, default=list)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL_SUMMARY", "Operational Summary"),
                            ("DEPARTMENT_PERFORMANCE", "Department Performance"),
                            ("SLA_REPORT", "SLA Report"),
                            ("COST_REPORT", "Cost Report"),
                            ("COMPLIANCE_REPORT", "Compliance Report"),
                            ("ENERGY_REPORT", "Energy Report"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("default_filters", models.JSONField(blank=True, default=dict)),
                ("columns_config", models.JSONField(blank=True, default=list)),
                ("chart_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_definitions",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_report_definitions",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("JSON", "JSON"), ("EXCEL", "Excel"), ("PDF", "PDF")],
                        default="JSON",
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="core.reportdefinition",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_report_runs",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("frequency_config", models.JSONField(blank=True, default=dict)),
                ("recipients", models.JSONField(blank=True, default=list)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("EXCEL", "Excel"), ("PDF", "PDF")], max_length=16
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_schedules",
                        to="core.user",
                    ),
                ),
                (
                    "report_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="core.reportdefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_report_schedules",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationalMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "snapshot_period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("module_name", models.CharField(max_length=64)),
                ("metric_key", models.CharField(max_length=128)),
                ("metric_value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("metric_unit", models.CharField(blank=True, max_length=32)),
                ("dimension_data", models.JSONField(blank=True, default=dict)),
                ("source_record_count", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_metric_snapshots",
                        to="core.department",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_metric_snapshots",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot_date", "module_name"],
                        name="ops_metric_date_module_idx",
                    ),
                    models.Index(
                        fields=["property", "snapshot_date"],
                        name="ops_metric_prop_date_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="operationalmetricsnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "snapshot_date",
                    "snapshot_period",
                    "module_name",
                    "property",
                    "department",
                    "metric_key",
                ),
                name="uniq_oper_metric_snapshot_dimension",
            ),
        ),
    ]
