# Generated by Django 5.0.6 on 2026-05-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_reportdatamartrun_reportdefinition_reportrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("PMS", "PMS"),
                            ("ACCOUNTING", "Accounting"),
                            ("BAS_IOT", "BAS / IoT"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ERROR", "Error"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="INACTIVE",
                        max_length=16,
                    ),
                ),
                ("base_url", models.CharField(blank=True, max_length=512)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("API_KEY", "API Key"),
                            ("BASIC", "Basic"),
                            ("BEARER_TOKEN", "Bearer Token"),
                            ("OAUTH2", "OAuth2"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="NONE",
                        max_length=32,
                    ),
                ),
                (
                    "credentials_secret_ref",
                    models.CharField(blank=True, max_length=512),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=15)),
                ("retry_policy", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_integration_providers",
                        to="core.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_integration_providers",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_type", models.CharField(max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                            ("DEAD_LETTER", "Dead Letter"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                ("external_event_id", models.CharField(blank=True, max_length=255)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("source_entity_type", models.CharField(blank=True, max_length=64)),
                ("source_entity_id", models.CharField(blank=True, max_length=128)),
                ("target_entity_type", models.CharField(blank=True, max_length=64)),
                ("target_entity_id", models.CharField(blank=True, max_length=128)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="core.integrationprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationJobAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.integrationjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "attempt_number"], name="int_attempt_job_num_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="integrationjob",
            index=models.Index(
                fields=["status", "next_retry_at"], name="integration_job_retry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationjob",
            index=models.Index(
                fields=["provider", "created_at"], name="int_job_provider_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationjob",
            constraint=models.UniqueConstraint(
                fields=("provider", "job_type", "idempotency_key"),
                name="uniq_integration_job_idem",
            ),
        ),
    ]
