import { useMemo, useState } from 'react'
import type { CAPEXRequest, Contract, POLineItem, PurchaseOrder, Supplier } from '../types/corporate.types'

export function SupplierForm({ orgId, initial, onSubmit, saving }: { orgId: number; initial?: Supplier | null; onSubmit: (p: Record<string, unknown>) => Promise<void> | void; saving?: boolean }) {
  const [f, setF] = useState({ supplier_code: initial?.supplier_code || '', name: initial?.name || '', contact_person: initial?.contact_person || '', email: initial?.email || '', phone: initial?.phone || '', address: initial?.address || '', tax_id: initial?.tax_id || '', category: initial?.category || '', status: initial?.status || 'ACTIVE', rating: initial?.rating ? String(initial.rating) : '', notes: initial?.notes || '' })
  const [error, setError] = useState<Record<string, string>>({})
  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    const n: Record<string, string> = {}
    if (!f.name.trim()) n.name = 'Name is required.'
    if (f.email && !/\S+@\S+\.\S+/.test(f.email)) n.email = 'Invalid email format.'
    if (f.rating && (Number(f.rating) < 1 || Number(f.rating) > 5)) n.rating = 'Rating must be between 1 and 5.'
    setError(n)
    if (Object.keys(n).length) return
    await onSubmit({ org_id: orgId, ...f, rating: f.rating ? Number(f.rating) : null })
  }
  return <form className='card-section' onSubmit={submit} aria-label='Supplier form'><div className='grid-form two'>
    {Object.entries({supplier_code:'Supplier Code',name:'Name',contact_person:'Contact Person',email:'Email',phone:'Phone',address:'Address',tax_id:'Tax ID',category:'Category'}).map(([k,l]) => <label key={k} className='field'>{l}<input className='input' value={(f as any)[k]} onChange={(e)=>setF((p)=>({...p,[k]:e.target.value}))}/>{error[k]?<span className='error-text'>{error[k]}</span>:null}</label>)}
    <label className='field'>Status<select className='input' value={f.status} onChange={(e)=>setF((p)=>({...p,status:e.target.value as any}))}><option>ACTIVE</option><option>INACTIVE</option><option>BLACKLISTED</option><option>ARCHIVED</option></select></label>
    <label className='field'>Rating<input className='input' value={f.rating} onChange={(e)=>setF((p)=>({...p,rating:e.target.value}))}/>{error.rating?<span className='error-text'>{error.rating}</span>:null}</label>
  </div><label className='field'>Notes<textarea className='input' rows={3} value={f.notes} onChange={(e)=>setF((p)=>({...p,notes:e.target.value}))} /></label>{f.status === 'BLACKLISTED' ? <p className='hint'>Warning: this supplier is blacklisted.</p> : null}<button className='button' disabled={saving}>{saving ? 'Saving...' : 'Save Supplier'}</button></form>
}

export function ContractForm({ orgId, initial, onSubmit, saving }: { orgId: number; initial?: Contract | null; onSubmit: (p: Record<string, unknown>) => Promise<void> | void; saving?: boolean }) {
  const [f, setF] = useState({ contract_code: initial?.contract_code || '', supplier_id: initial?.supplier_id ? String(initial.supplier_id) : '', title: initial?.title || '', description: initial?.description || '', contract_type: initial?.contract_type || '', status: initial?.status || 'DRAFT', effective_date: initial?.effective_date || '', expiry_date: initial?.expiry_date || '', renewal_due_at: initial?.renewal_due_at || '', contract_value: initial?.contract_value || '0', currency: initial?.currency || 'USD', attachment_id: initial?.attachment_id ? String(initial.attachment_id) : '', owner_id: initial?.owner_id ? String(initial.owner_id) : '' })
  const [error, setError] = useState<Record<string, string>>({})
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const n: Record<string, string> = {}; if (!f.supplier_id) n.supplier_id = 'Supplier is required.'; if (!f.title.trim()) n.title = 'Title is required.'; if (f.effective_date && f.expiry_date && f.expiry_date < f.effective_date) n.expiry_date = 'Expiry date must be after effective date.'; if (f.renewal_due_at && f.expiry_date && f.renewal_due_at > f.expiry_date) n.renewal_due_at = 'Renewal due must be before/equal expiry date.'; if (Number(f.contract_value) < 0) n.contract_value = 'Contract value cannot be negative.'; setError(n); if (Object.keys(n).length) return; await onSubmit({ org_id: orgId, ...f, supplier_id: Number(f.supplier_id), contract_value: f.contract_value, attachment_id: f.attachment_id ? Number(f.attachment_id) : null, owner_id: f.owner_id ? Number(f.owner_id) : null, renewal_due_at: f.renewal_due_at || null }) }
  return <form className='card-section' onSubmit={submit} aria-label='Contract form'><div className='grid-form two'>
    {['contract_code','supplier_id','title','description','contract_type','effective_date','expiry_date','renewal_due_at','contract_value','currency','attachment_id','owner_id'].map((k)=><label key={k} className='field'>{k}<input className='input' type={k.includes('date')?'date':'text'} value={(f as any)[k]} onChange={(e)=>setF((p)=>({...p,[k]:e.target.value}))}/>{error[k]?<span className='error-text'>{error[k]}</span>:null}</label>)}
    <label className='field'>Status<select className='input' value={f.status} onChange={(e)=>setF((p)=>({...p,status:e.target.value as any}))}><option>DRAFT</option><option>ACTIVE</option><option>EXPIRED</option><option>TERMINATED</option><option>RENEWAL_DUE</option><option>ARCHIVED</option></select></label>
  </div><button className='button' disabled={saving}>{saving ? 'Saving...' : 'Save Contract'}</button></form>
}

export function computePOLine(li: POLineItem) { const q = Number(li.quantity || 0); const up = Number(li.unit_price || 0); const tr = Number(li.tax_rate || 0); const d = Number(li.discount_amount || 0); const base = q * up; const tax = base * tr; return +(base + tax - d).toFixed(2) }

export function PurchaseOrderForm({ orgId, initial, readOnly, onSubmit, saving }: { orgId: number; initial?: PurchaseOrder | null; readOnly?: boolean; onSubmit: (p: Record<string, unknown>) => Promise<void> | void; saving?: boolean }) {
  const [f, setF] = useState({ po_number: initial?.po_number || '', supplier_id: initial?.supplier_id ? String(initial.supplier_id) : '', contract_id: initial?.contract_id ? String(initial.contract_id) : '', property_id: initial?.property_id ? String(initial.property_id) : '', department_id: initial?.department_id ? String(initial.department_id) : '', requester_id: initial?.requester_id ? String(initial.requester_id) : '', approver_id: initial?.approver_id ? String(initial.approver_id) : '', secondary_approver_id: initial?.secondary_approver_id ? String(initial.secondary_approver_id) : '', priority: initial?.priority || 'MEDIUM', requested_date: initial?.requested_date || '', required_by: initial?.required_by || '', currency: initial?.currency || 'USD', notes: initial?.notes || '' })
  const [lineItems, setLineItems] = useState<POLineItem[]>(initial?.line_items?.length ? initial.line_items.map((x) => ({ ...x, quantity: String(x.quantity), unit_price: String(x.unit_price), tax_rate: String(x.tax_rate), discount_amount: String(x.discount_amount) })) : [{ item_name: '', description: '', quantity: '1', unit_price: '0', tax_rate: '0', discount_amount: '0' }])
  const [error, setError] = useState('')
  const totals = useMemo(() => {
    const subtotal = lineItems.reduce((s, li) => s + Number(li.quantity || 0) * Number(li.unit_price || 0), 0)
    const tax = lineItems.reduce((s, li) => s + Number(li.quantity || 0) * Number(li.unit_price || 0) * Number(li.tax_rate || 0), 0)
    const discount = lineItems.reduce((s, li) => s + Number(li.discount_amount || 0), 0)
    return { subtotal, tax, discount, total: subtotal + tax - discount }
  }, [lineItems])
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!lineItems.length || lineItems.every((x) => !x.item_name.trim())) { setError('At least one line item is required.'); return }; if (lineItems.some((x) => Number(x.quantity) < 0 || Number(x.unit_price) < 0 || Number(x.tax_rate) < 0 || Number(x.discount_amount) < 0)) { setError('Negative values are not allowed.'); return } ; setError(''); await onSubmit({ org_id: orgId, ...f, supplier_id: Number(f.supplier_id), requester_id: Number(f.requester_id), contract_id: f.contract_id ? Number(f.contract_id) : null, property_id: f.property_id ? Number(f.property_id) : null, department_id: f.department_id ? Number(f.department_id) : null, approver_id: f.approver_id ? Number(f.approver_id) : null, secondary_approver_id: f.secondary_approver_id ? Number(f.secondary_approver_id) : null, line_items: lineItems.map((li) => ({ ...li })) }) }
  return <form className='card-section' onSubmit={submit} aria-label='Purchase order form'><div className='grid-form two'>{['po_number','supplier_id','contract_id','property_id','department_id','requester_id','approver_id','secondary_approver_id','requested_date','required_by','currency'].map((k)=><label className='field' key={k}>{k}<input type={k.includes('date')?'date':'text'} disabled={readOnly} className='input' value={(f as any)[k]} onChange={(e)=>setF((p)=>({...p,[k]:e.target.value}))}/></label>)}<label className='field'>priority<select disabled={readOnly} className='input' value={f.priority} onChange={(e)=>setF((p)=>({...p,priority:e.target.value as any}))}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label></div>
  <div className='section-head'><h3>Line Items</h3><button type='button' className='button secondary small' disabled={readOnly} onClick={()=>setLineItems((p)=>([...p,{ item_name: '', description: '', quantity: '1', unit_price: '0', tax_rate: '0', discount_amount: '0' }]))}>Add</button></div>
  {lineItems.map((li, i)=><div className='grid-form' key={i}><input aria-label={`item_name_${i}`} className='input' disabled={readOnly} placeholder='Item name' value={li.item_name} onChange={(e)=>setLineItems((p)=>p.map((x,idx)=>idx===i?{...x,item_name:e.target.value}:x))}/><input aria-label={`quantity_${i}`} className='input' disabled={readOnly} value={li.quantity} onChange={(e)=>setLineItems((p)=>p.map((x,idx)=>idx===i?{...x,quantity:e.target.value}:x))}/><input aria-label={`unit_price_${i}`} className='input' disabled={readOnly} value={li.unit_price} onChange={(e)=>setLineItems((p)=>p.map((x,idx)=>idx===i?{...x,unit_price:e.target.value}:x))}/><input aria-label={`tax_rate_${i}`} className='input' disabled={readOnly} value={li.tax_rate} onChange={(e)=>setLineItems((p)=>p.map((x,idx)=>idx===i?{...x,tax_rate:e.target.value}:x))}/><input aria-label={`discount_amount_${i}`} className='input' disabled={readOnly} value={li.discount_amount} onChange={(e)=>setLineItems((p)=>p.map((x,idx)=>idx===i?{...x,discount_amount:e.target.value}:x))}/><span>{computePOLine(li).toFixed(2)}</span><button type='button' className='button secondary small' disabled={readOnly} onClick={()=>setLineItems((p)=>p.filter((_,idx)=>idx!==i))}>Remove</button></div>)}
  <p>Subtotal: {totals.subtotal.toFixed(2)} | Tax: {totals.tax.toFixed(2)} | Discount: {totals.discount.toFixed(2)} | Total: {totals.total.toFixed(2)}</p>
  <label className='field'>Notes<textarea className='input' disabled={readOnly} value={f.notes} onChange={(e)=>setF((p)=>({...p,notes:e.target.value}))}/></label>{error?<p className='error-text'>{error}</p>:null}<button className='button' disabled={saving || readOnly}>{saving ? 'Saving...' : 'Save PO'}</button></form>
}

export function CapexForm({ orgId, initial, onSubmit, saving, highValueThreshold = 5000 }: { orgId: number; initial?: CAPEXRequest | null; onSubmit: (p: Record<string, unknown>) => Promise<void> | void; saving?: boolean; highValueThreshold?: number }) {
  const [f, setF] = useState({ capex_number: initial?.capex_number || '', title: initial?.title || '', description: initial?.description || '', property_id: initial?.property_id ? String(initial.property_id) : '', department_id: initial?.department_id ? String(initial.department_id) : '', requester_id: initial?.requester_id ? String(initial.requester_id) : '', approver_id: initial?.approver_id ? String(initial.approver_id) : '', secondary_approver_id: initial?.secondary_approver_id ? String(initial.secondary_approver_id) : '', category: initial?.category || '', estimated_amount: initial?.estimated_amount || '', approved_amount: initial?.approved_amount || '0', currency: initial?.currency || 'USD', justification: initial?.justification || '', business_impact: initial?.business_impact || '' })
  const [error, setError] = useState<Record<string, string>>({})
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const n: Record<string, string> = {}; if (!f.title.trim()) n.title = 'Title is required.'; if (!(Number(f.estimated_amount) > 0)) n.estimated_amount = 'Estimated amount must be positive.'; if (Number(f.approved_amount) > Number(f.estimated_amount)) n.approved_amount = 'Approved amount cannot exceed estimated amount.'; if (!f.justification.trim()) n.justification = 'Justification is required.'; if (Number(f.estimated_amount) >= highValueThreshold && !f.business_impact.trim()) n.business_impact = 'Business impact is required for high-value CAPEX.'; setError(n); if (Object.keys(n).length) return; await onSubmit({ org_id: orgId, ...f, requester_id: Number(f.requester_id), property_id: f.property_id ? Number(f.property_id) : null, department_id: f.department_id ? Number(f.department_id) : null, approver_id: f.approver_id ? Number(f.approver_id) : null, secondary_approver_id: f.secondary_approver_id ? Number(f.secondary_approver_id) : null }) }
  return <form className='card-section' onSubmit={submit} aria-label='CAPEX form'><div className='grid-form two'>{['capex_number','title','description','property_id','department_id','requester_id','approver_id','secondary_approver_id','category','estimated_amount','approved_amount','currency','justification','business_impact'].map((k)=><label className='field' key={k}>{k}<input className='input' value={(f as any)[k]} onChange={(e)=>setF((p)=>({...p,[k]:e.target.value}))}/>{error[k]?<span className='error-text'>{error[k]}</span>:null}</label>)}</div><button className='button' disabled={saving}>{saving?'Saving...':'Save CAPEX'}</button></form>
}
